insert into category values(1,'Academics')
insert into category values(2,'Fiction')
insert into category values(3,'NonFiction')
insert into sub_category values(11,'Engineering',1)
insert into sub_category values(12,'Medical',1)
insert into sub_category values(13,'Mystery',2)
insert into sub_category values(14,'Romance',2)
insert into sub_category values(15,'Biographies',3)
insert into sub_category values(16,'History',3)
insert into book values(101,'Engineering Mathematics',null,null,11)
insert into book values(102,'C++',null,null,11)
insert into book values(103,'If tomorrow comes',null,null,13)
insert into book values(104,'APj Abdul Kalam',null,null,15)
